#!/bin/bash -e

. settings

REMOTE_BRANCH=rpm/${FOREMAN_VERSION}

cd "$PACKAGING_DIR"

git fetch $PACKAGING_GIT_REMOTE
git checkout -b rpm/release-$PROJECT-$FULLVERSION $PACKAGING_GIT_REMOTE/$REMOTE_BRANCH

if [[ $FULLVERSION == *-RC* ]] ; then
	if [[ FULLVERSION == *-RC1 ]] ; then
		echo "TODO: bump release"
	fi
	obal update -e version=${FULLVERSION%%-RC*} -e prerelease=${FULLVERSION##*-} -e release=keep $RPM_PACKAGES
else
	obal update -e version=$FULLVERSION $RPM_PACKAGES
fi

if [[ $PACKAGING_PR == true ]] ; then
	git phr -m "Release $FULLVERSION" -b "$REMOTE_BRANCH"
else
	git push $PACKAGING_GIT_REMOTE HEAD:$REMOTE_BRANCH
fi
