#!/bin/bash -e

. settings

mkdir -p "$RPMDIR"
cd "$RPMDIR"

tags=""

for os in $OSES; do
  versioned_tags=$(echo ${KOJI_TAGS} | sed "s/@VERSION@/$VERSION/g; s/@OS@/$os/g")
  for tag in ${versioned_tags}; do
    tags="$tags $tag"
  done
  tags=$(echo $tags | sed 's/ /\n/g'| sort -u | xargs)
done

for tag in $tags; do
  koji list-tagged --latest --quiet --inherit --sigs $tag
done \
  | sed 's!^!:!' \
  | perl -ane '$F[1] =~ s!\.src$!! or next; $R{$F[1]} = 1; $S{$F[1]} = 1 if lc($F[0]) eq lc(":'$GPGKEY'");
    END { print map "$_\n", grep { not exists $S{$_} } sort keys %R }' \
  | xargs --no-run-if-empty -P 2 -n 1 koji download-build --debuginfo
