#!/bin/bash -e

. settings

mkdir -p "$TARDIR"

for project in $TAR_PROJECTS ; do
	filename="$project-$FULLVERSION.tar.bz2"
	wget "https://downloads.theforeman.org/$project/$filename" -O "$TARDIR/$filename"
done
