#!/bin/bash -e

. settings

mkdir -p "$RPMDIR"
cd "$RPMDIR"

for j in $OSES; do
  tags=foreman-$VERSION-$j
  [[ $j =~ rhel ]] && tags="$tags foreman-$VERSION-nonscl-$j"
  for i in $tags; do
    koji list-tagged --latest --quiet --inherit --sigs $i
  done \
    | sed 's!^!:!' \
    | perl -ane '$F[1] =~ s!\.src$!! or next; $R{$F[1]} = 1; $S{$F[1]} = 1 if lc($F[0]) eq lc(":'$GPGKEY'");
      END { print map "$_\n", grep { not exists $S{$_} } sort keys %R }' \
    | xargs -P 3 -n 1 koji download-build --debuginfo $i
done
