#!/bin/bash -e

. settings

if [[ ! -d $KEYDIR ]] ; then
	echo "Keydir $KEYDIR doesn't exist"
	exit 1
fi

if [[ -z $FULLGPGKEY ]] ; then
	echo "FULLGPGKEY must be set"
	gpg2 --homedir "$KEYDIR" --list-key "$SIGNER"
	exit 2
fi

pass show -c "$PASS_NAME_GPG"
gpg2 --homedir "$KEYDIR" --export-secret-keys -a "$FULLGPGKEY" | pass insert --multiline "$PASS_NAME_KEY"
