#!/bin/bash -e

. settings

if [[ ! -d $KEYDIR ]] ; then
	echo "Keydir $KEYDIR doesn't exist"
	exit 1
fi

if [[ -z $FULLGPGKEY ]] ; then
	echo "FULLGPGKEY must be set"
	gpg2 --homedir "$KEYDIR" --list-key "$SIGNER"
	exit 2
fi

CHECKOUT="${GIT_DIR}/theforeman.org"

gpg2 --homedir "$KEYDIR" --armor --export "$FULLGPGKEY" > "${CHECKOUT}/static/keys/${FULLGPGKEY}.pub"

echo "Fill in any FIXME's and then add this to ${CHECKOUT}/security.md"
gpg2 --homedir "$KEYDIR" --fingerprint "$FULLGPGKEY"
cat <<EOF
      <tr>
        <td><a href="{{ site.baseurl }}/static/keys/${FULLGPGKEY}.pub">${FULLGPGKEY}</a></td>
        <td>FIXME: fingerprint</td>
        <td>${SIGNER_NAME} (${VERSION})</td>
        <td style='white-space:nowrap'>$(date +%Y-%m-%d) (FIXME: check)</td>
        <td style='white-space:nowrap'>FIXME: end date</td>
        <td style='white-space:nowrap'></td>
        <td></td>
      </tr>
EOF
