#!/bin/bash -e

. settings

if [[ ! -d $KEYDIR ]] ; then
	echo "Keydir $KEYDIR doesn't exist"
	exit 1
fi

if [[ -z $FULLGPGKEY ]] ; then
	echo "FULLGPGKEY must be set"
	gpg2 --homedir "$KEYDIR" --list-key "$SIGNER"
	exit 2
fi

copy_gpg_key
gpg2 --homedir "$KEYDIR" --export-secret-keys -a "$FULLGPGKEY" | gopass insert --multiline "$PASS_NAME_KEY"
