#!/bin/bash -e

. settings

if [[ -d $KEYDIR ]] ; then
	echo "Keydir $KEYDIR already exists"
	exit 1
fi

mkdir -m 0700 $KEYDIR

( gopass show "$PASS_NAME_GPG" 2> /dev/null || gopass generate "$PASS_NAME_GPG" 20 ) > /dev/null

GPG_SETTINGS=$(mktemp)
trap "rm -f $GPG_SETTINGS" EXIT
cat > $GPG_SETTINGS <<EOF
     %echo Generating GPG keys
     Key-Type: RSA
     Key-Length: 4096
     Name-Real: Foreman Automatic Signing Key
     Name-Comment: $VERSION
     Name-Email: $SIGNER
     Expire-Date: 1y
     Passphrase: $(gopass show "$PASS_NAME_GPG")
     # Do a commit here, so that we can later print "done" :-)
     %commit
     %echo done
EOF
gpg2 --homedir $KEYDIR --batch --gen-key $GPG_SETTINGS

echo "Now set GPGKEY and FULLGPGKEY in releases/$VERSION/settings"
gpg2 --homedir "$KEYDIR" --list-key "$SIGNER"
