#!/bin/bash -e

. settings

sign() {
	copy_gpg_key
	for project in $TAR_PROJECTS ; do
		filename="$project-$FULLVERSION.tar.bz2"
		gpg2 --homedir "$KEYDIR" -b -u "$SIGNER" "$TARDIR/$filename"
	done
}

upload() {
	local files="{'files': {"
	for project in $TAR_PROJECTS ; do
		filename="$project-$FULLVERSION.tar.bz2"
		files+="'${TARDIR}/${filename}.sig': '${project}/${filename}.sig',"
	done
	files+="},"
	files+="'docroot': '${DOCROOT}'"
	files+="}"

	copy_unix_pass
	ansible-playbook --ask-become-pass --inventory=$HOSTS --extra-vars="$files" upload_tarball_signatures.yaml
}

if [[ ! -d "$TARDIR" ]] ; then
	echo "Tar directory $TARDIR doesn't exist"
	exit 1
fi

sign
upload
