#!/bin/bash -e

. settings

copy_gpg_key

cat > ~/.rpmmacros <<EOF
%_gpg_path $KEYDIR
%_gpg_name $SIGNER
EOF

rpmdev-vercmp $(rpm --query --queryformat='%{EVR}' rpm) 4.16.0 || RESULT=$?
if [[ $RESULT == "11" ]]; then
	SIGN_FLAGS="--rpmv3"
else
	SIGN_FLAGS=""
fi

if [[ -n $1 ]] ; then
	echo "$@" | xargs $XARGS_JOBS rpmsign --addsign $SIGN_FLAGS
else
	find "$RPMDIR" -name '*.rpm' | xargs $XARGS_JOBS rpmsign --addsign $SIGN_FLAGS
fi
