#!/bin/bash -e

. settings

if [[ ! -d $KEYDIR ]] ; then
	echo "Keydir $KEYDIR doesn't exist"
	exit 1
fi

if [[ -z $FULLGPGKEY ]] ; then
	echo "FULLGPGKEY must be set"
	exit 2
fi

gpg2 --homedir "$KEYDIR" --armor --export "$FULLGPGKEY" | gpg2 --import
gpg2 --edit-key "$FULLGPGKEY"
