#!/bin/bash -e

. settings

copy_gpg_key

cat > ~/.rpmmacros <<EOF
%_gpg_path $KEYDIR
%_gpg_name $SIGNER
EOF

if [[ -n $1 ]] ; then
	echo "$@" | xargs $XARGS_JOBS rpmsign --addsign
else
	find "$RPMDIR" -name '*.rpm' | xargs $XARGS_JOBS rpmsign --addsign
fi
