#!/bin/bash -e

. settings

if [[ -z $1 ]] ; then
	PROJECTS=$TAR_PROJECTS
else
	PROJECTS=$@
fi

for project in $PROJECTS ; do
	(
		cd "$GIT_DIR/$project"
		if ! git diff --quiet --exit-code ; then
			echo "Checkout in $PWD is dirty"
			exit 1
		fi
	)
done

for project in $PROJECTS ; do
	(
		cd "$GIT_DIR/$project"
		git checkout "${VERSION}-stable"
		git pull --quiet
		echo "$FULLVERSION" > VERSION
		git commit --quiet --all --message "Release $FULLVERSION"
		if [ -x ./extras/changelog ] ; then
			./extras/changelog
			git commit --amend --quiet --all --no-edit
		fi
		if [ -x ./extra/changelog ] ; then
			./extra/changelog
			git commit --amend --quiet --all --no-edit
		fi
		git tag --sign --message "Release $FULLVERSION" "$FULLVERSION"
		echo "Tagged ${project} ${FULLVERSION}"
	)
done
