#!/bin/bash -e

. settings

if [[ -z $1 ]] ; then
	PROJECTS=$TAR_PROJECTS
else
	PROJECTS=$@
fi

for project in $PROJECTS ; do
	(
		cd "$GIT_DIR/$project"
		if ! git diff --quiet --exit-code ; then
			echo "Checkout in $PWD is dirty"
			exit 1
		fi
	)
done

for project in $PROJECTS ; do
	(
		cd "$GIT_DIR/$project"
		git checkout "${VERSION}-stable"
		git pull --quiet
		echo "$FULLVERSION" > VERSION
		if [[ $project != foreman-installer ]] ; then
			./extras/changelog
		fi
		git commit --quiet --all --message "Release $FULLVERSION"
		git tag --sign --message "Release $FULLVERSION" "$FULLVERSION"
	)
done
